import test from "node:test";
import assert from "node:assert/strict";
import { ControlPlane, FunctionProvider, HelpPc1Adapter, Vision2Adapter, createRpcHandler, mcpToolDefinitions } from "../src/index.js";
function ids() { let n = 0; return () => `id-${++n}`; }
function plane({ invoke = async () => ({ ok: true }), policy } = {}) { return new ControlPlane({ providers: [new FunctionProvider("fake", invoke)], policy, idFactory: ids() }); }

test("desktop ownership is exclusive across sessions", () => { const cp = plane(); const first = cp.createSession({ desktopId: "desktop-A" }); assert.throws(() => cp.createSession({ desktopId: "desktop-A" }), (error) => error.code === "DESKTOP_OWNED"); cp.releaseDesktop(first.id); const second = cp.createSession({ desktopId: "desktop-A" }); assert.equal(cp.snapshot().desktopOwners[0][1], second.id); });

test("idempotency returns original action and executes once", async () => { let calls = 0; const cp = plane({ invoke: async () => ({ calls: ++calls }) }); const session = cp.createSession({ desktopId: "desktop-A" }); const spec = { provider: "fake", type: "mouse.click", idempotencyKey: "click-1" }; const first = cp.enqueueAction(session.id, spec); const duplicate = cp.enqueueAction(session.id, spec); assert.equal(duplicate.id, first.id); await cp.drain(); assert.equal(calls, 1); assert.equal(cp.getAction(first.id).status, "succeeded"); });

test("credential and CAPTCHA automation remains prohibited", () => { const cp = plane(); const session = cp.createSession({ desktopId: "desktop-A" }); assert.throws(() => cp.enqueueAction(session.id, { provider: "fake", type: "captcha.solve" }), /not supported/); assert.throws(() => cp.enqueueAction(session.id, { provider: "fake", type: "credential.fill" }), /not supported/); });

test("destructive actions remain disabled by default", () => { const cp = plane(); const session = cp.createSession({ desktopId: "desktop-A" }); assert.throws(() => cp.enqueueAction(session.id, { provider: "fake", type: "file.delete", destructive: true }), (error) => error.code === "DESTRUCTIVE_DISABLED"); });

test("automatic execution retry requires confirmed not-dispatched evidence", async () => { let calls = 0; const cp = plane({ invoke: async () => { calls += 1; if (calls === 1) throw Object.assign(new Error("connection refused before dispatch"), { retryable: true, code: "PRE_DISPATCH", category: "transient", dispatchState: "not_dispatched", outcomeUncertain: false }); return { ok: true }; } }); const session = cp.createSession({ desktopId: "desktop-A" }); const action = cp.enqueueAction(session.id, { provider: "fake", type: "screen.read", maxAttempts: 2 }); assert.equal((await cp.processNext()).status, "retry_wait"); const second = await cp.processNext(); assert.equal(second.status, "succeeded"); assert.equal(second.executionAttempts, 2); assert.equal(second.attempts, 2); assert.equal(calls, 2); assert.equal(cp.getAction(action.id).status, "succeeded"); });

test("executing cancellation with unknown dispatch outcome enters uncertainty instead of blind retry", async () => { let started; const ready = new Promise((resolve) => { started = resolve; }); const cp = plane({ invoke: ({ signal }) => new Promise((_resolve, reject) => { started(); signal.addEventListener("abort", () => reject(signal.reason ?? new Error("aborted")), { once: true }); }) }); const session = cp.createSession({ desktopId: "desktop-A" }); const action = cp.enqueueAction(session.id, { provider: "fake", type: "mouse.move", maxReconciliationAttempts: 1 }); const pending = cp.processNext(); await ready; cp.cancelAction(action.id, "operator_stop"); const result = await pending; assert.equal(result.status, "uncertain_outcome"); assert.equal(result.executionAttempts, 1); });

test("resource lanes still separate pointer/keyboard from observation", () => { const cp = plane(); const session = cp.createSession({ desktopId: "desktop-A" }); const mouse = cp.enqueueAction(session.id, { provider: "fake", type: "mouse.move" }); const keyboard = cp.enqueueAction(session.id, { provider: "fake", type: "keyboard.press" }); const screenshot = cp.enqueueAction(session.id, { provider: "fake", type: "screenshot.capture" }); assert.equal(cp.leaseNext({ workerId: "one" }).id, mouse.id); assert.equal(cp.leaseNext({ workerId: "two" }).id, screenshot.id); assert.equal(cp.leaseNext({ workerId: "three" }), null); assert.ok(keyboard.lanes.includes("keyboard-mouse:desktop-A")); });

test("audit log remains correlation-filterable", async () => { const cp = plane(); const session = cp.createSession({ desktopId: "desktop-A" }); const action = cp.enqueueAction(session.id, { provider: "fake", type: "screen.read", correlationId: "corr-1" }); await cp.processNext(); const audit = cp.getAuditLog({ correlationId: "corr-1" }); assert.ok(audit.length >= 3); assert.ok(audit.every((entry) => entry.correlationId === "corr-1")); assert.equal(cp.getAction(action.id).status, "succeeded"); });

test("help-pc-1 exact envelope and vision-2 generic boundary coexist", async () => { const calls = []; const help = new HelpPc1Adapter({ invoke: async (request) => (calls.push(["help", request]), { request_id: request.request_id, action: request.action, ok: true, status: "dry_run", dry_run: true }) }); const vision = new Vision2Adapter({ invoke: async (request) => (calls.push(["vision", request]), { seen: true }) }); const cp = new ControlPlane({ providers: [help, vision], idFactory: ids() }); const session = cp.createSession({ desktopId: "desktop-A" }); cp.enqueueAction(session.id, { provider: "help-pc-1", type: "mouse.click", input: { x: 10, y: 20 } }); cp.enqueueAction(session.id, { provider: "vision-2", type: "screen.describe", permission: "desktop.observe" }); await cp.drain(); assert.deepEqual(calls[0][1], { request_id: "id-2", action: "mouse.click", params: { x: 10, y: 20 }, dry_run: true }); assert.equal(calls[1][1].tool, "screen.describe"); });

test("RPC/MCP status exposes separated attempt counters", async () => { const cp = plane(); const rpc = createRpcHandler(cp); const session = await rpc("session.create", { desktopId: "desktop-A" }); const action = await rpc("action.enqueue", { sessionId: session.id, action: { provider: "fake", type: "screen.read" } }); const status = await rpc("action.status", { actionId: action.id }); assert.equal(status.executionAttempts, 0); assert.equal(status.verificationAttempts, 0); assert.equal(status.reconciliationAttempts, 0); assert.ok(mcpToolDefinitions().some((tool) => tool.rpcMethod === "action.status")); });
