import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { TOOL_CATALOG,toolManifest } from "../src/pc-ops/catalog.js";
import { assertNoSafetyBypass,assertPathAllowed,normalizePcPath,pathPolicyContract } from "../src/pc-ops/path-policy.js";
import { ManagedOperationStore } from "../src/pc-ops/managed-operations.js";
import { PcOpsGateway } from "../src/pc-ops/gateway.js";
const EXPECTED=["health.get","capabilities.get","shell.run","shell.session.start","shell.session.read","shell.session.write_stdin","shell.session.terminate","fs.list","fs.stat","fs.read_text","fs.read_bytes","fs.hash","fs.find","fs.write_text","fs.append_text","fs.mkdir","fs.copy","fs.move","fs.delete","log.tail","log.read_since","log.search","process.list","process.inspect","process.start","process.status","process.read_output","process.terminate","windows.list","screenshot.capture","uia.snapshot","uia.inspect","uia.invoke","uia.focus","uia.set_value","clipboard.get","clipboard.set","action.preflight","outcome.lookup","system.info","system.resources"];
function canonical(value){if(Array.isArray(value))return"["+value.map(canonical).join(",")+"]";if(value&&typeof value==="object")return"{"+Object.keys(value).sort().map((k)=>JSON.stringify(k)+":"+canonical(value[k])).join(",")+"}";return JSON.stringify(value);}
class FakeControl{constructor(){this.actions=new Map();this.byIdem=new Map();this.n=0;}enqueueAction(_session,spec){if(this.byIdem.has(spec.idempotencyKey))return structuredClone(this.actions.get(this.byIdem.get(spec.idempotencyKey)));const id="a"+(++this.n),status=spec.confirmation==="required"?"awaiting_confirmation":"queued",a={id,status,...spec,result:null,error:null};this.actions.set(id,a);this.byIdem.set(spec.idempotencyKey,id);return structuredClone(a);}getAction(id){return structuredClone(this.actions.get(id));}confirmAction(id){const a=this.actions.get(id);a.status="queued";return structuredClone(a);}async processNext(){const a=[...this.actions.values()].find((x)=>x.status==="queued");if(!a)return null;a.status="succeeded";a.result={data:{handle_id:a.type?.includes("session")?"session-1":"remote-1",session_id:a.type?.includes("session")?"session-1":null,cursor:{version:"pc_executor.stream_cursor.v1",handle_id:"remote-1",stdout_offset:1,stderr_offset:0}}};return structuredClone(a);}}
const allTransport={supports:()=>true,health:async()=>({queue_reachable:true,relay_alive:true,last_processed_request:"r0"})};
test("catalog has exact stable v1 surface and structured-first metadata",()=>{assert.deepEqual(TOOL_CATALOG.map((x)=>x.name),EXPECTED);assert.equal(new Set(EXPECTED).size,41);assert.equal(TOOL_CATALOG.find((x)=>x.name==="shell.run").shell_fallback,true);assert.equal(TOOL_CATALOG.find((x)=>x.name==="fs.read_text").preferred_structured,true);assert.equal(TOOL_CATALOG.find((x)=>x.name==="fs.delete").destructive_level,"high");const copy=TOOL_CATALOG.find((x)=>x.name==="fs.copy").input_schema;assert.deepEqual(copy.required,["source","destination"]);assert.equal(Object.hasOwn(copy.properties,"path"),false);assert.ok(TOOL_CATALOG.find((x)=>x.name==="process.start").input_schema.properties.operation_id);});
test("protected path and client bypass fail closed",()=>{assert.equal(normalizePcPath("E:/tmp/../work"),"E:\\work");assert.throws(()=>assertPathAllowed("E:\\manhwa\\chapter1"),{code:"PC_OPS_PROTECTED_PATH"});assert.throws(()=>assertNoSafetyBypass({safety_bypass:true}),{code:"PC_OPS_SAFETY_BYPASS_FORBIDDEN"});assert.equal(pathPolicyContract().client_bypass,false);});
test("current relay gate rejects unproduced structured ops",async()=>{const g=new PcOpsGateway({controlPlane:new FakeControl(),transport:{supports:(n)=>["shell.run"].includes(n),health:allTransport.health},sessionId:"s"});await assert.rejects(()=>g.call("fs.read_text",{path:"E:\\work\\a.txt"},{requestId:"r1"}),{code:"PC_OPS_PRODUCER_PENDING"});});
test("managed start is not duplicated and cursor reads bind to operation",async()=>{const cp=new FakeControl(),store=new ManagedOperationStore(),g=new PcOpsGateway({controlPlane:cp,transport:allTransport,sessionId:"s",managedStore:store});const first=await g.call("process.start",{operation_id:"build-1",argv:["git","status"]},{requestId:"r-start"});const again=await g.call("process.start",{operation_id:"build-1",argv:["git","status"]},{requestId:"r-start-2"});assert.equal(first.action_id,again.action_id);assert.equal(cp.n,1);const read=await g.call("process.read_output",{operation_id:"build-1"},{requestId:"r-read"});assert.equal(read.operation.remote_handle.handle_id,"remote-1");const readAction=cp.getAction(read.action_id);assert.equal(readAction.input.handle_id,"remote-1");assert.equal(Object.hasOwn(readAction.input,"operation_id"),false);assert.equal(Object.hasOwn(cp.getAction(first.action_id).input,"operation_id"),false);});
test("destructive delete requires explicit confirmation",async()=>{const cp=new FakeControl(),g=new PcOpsGateway({controlPlane:cp,transport:allTransport,sessionId:"s"});const pending=await g.call("fs.delete",{path:"E:\\work\\old.txt"},{requestId:"del-1"});assert.equal(pending.status,"awaiting_confirmation");const done=await g.call("fs.delete",{path:"E:\\work\\old.txt"},{requestId:"del-1",confirm:true});assert.equal(done.status,"succeeded");});
test("health contains SHAs and transport state",async()=>{const g=new PcOpsGateway({controlPlane:new FakeControl(),transport:allTransport,sessionId:"s",implementationSha:"impl",executorSha:"exec",relaySha:"relay",producerMatrix:{ready_to_migrate:false}});const h=await g.call("health.get",{}, {requestId:"health-1"});assert.equal(h.data.implementation_sha,"impl");assert.equal(h.data.executor_sha,"exec");assert.equal(h.data.queue_transport.queue_reachable,true);assert.equal(h.data.ready_to_migrate,false);});
test("committed tool manifest hash is deterministic",()=>{const parsed=JSON.parse(readFileSync("conformance/pc_ops.gateway.v1/tool-manifest.json","utf8"));assert.deepEqual(parsed,toolManifest());const actual=createHash("sha256").update(canonical(parsed)).digest("hex"),expected=readFileSync("conformance/pc_ops.gateway.v1/tool-manifest.sha256","utf8").trim();assert.equal(actual,expected);});
test("E2E migration report stays fail-closed until structured producer fixtures exist",()=>{const report=JSON.parse(readFileSync("conformance/reports/pc-ops-gateway-e2e-v1.json","utf8"));assert.equal(report.ready_to_migrate,false);assert.equal(report.producer_gate.relay_structured_ops_fixture_pack,"pending");});

test("E2E scenario fixture enumerates restart boundaries deterministically",()=>{const scenarios=JSON.parse(readFileSync("conformance/pc_ops.gateway.v1/e2e-scenarios.json","utf8"));assert.deepEqual(scenarios.scenarios.map((x)=>x.id),["read-edit-verify","log-process-lifecycle","long-powershell-session","git-repo-status-structured","screenshot-uia-observation","protected-path-rejection","unknown-outcome-reconciliation"]);assert.ok(scenarios.scenarios.every((x)=>Array.isArray(x.restart_boundaries)&&x.restart_boundaries.length>0));const actual=createHash("sha256").update(canonical(scenarios)).digest("hex"),expected=readFileSync("conformance/pc_ops.gateway.v1/e2e-scenarios.sha256","utf8").trim();assert.equal(actual,expected);});
