import { createHash, randomUUID } from "node:crypto";
import { CURRENT_RELAY_BASELINE,GATEWAY_VERSION,getToolMetadata,toolManifest } from "./catalog.js";
import { guardToolPaths,pathPolicyContract } from "./path-policy.js";
import { ManagedOperationStore } from "./managed-operations.js";
const TERMINAL=new Set(["succeeded","blocked","cancelled","failed"]);
const START_KIND=new Map([["process.start","process"],["shell.session.start","shell_session"]]);
const OPERATION_TOOLS=/^(?:process\.(?:status|read_output|terminate)|shell\.session\.(?:read|write_stdin|terminate))$/;
function canonical(value){if(Array.isArray(value))return"["+value.map(canonical).join(",")+"]";if(value&&typeof value==="object")return"{"+Object.keys(value).sort().map((k)=>JSON.stringify(k)+":"+canonical(value[k])).join(",")+"}";return JSON.stringify(value);}
function digest(v){return createHash("sha256").update(canonical(v)).digest("hex");}
function resultData(action){return action?.result?.result?.data??action?.result?.data??action?.executionResult?.data??action?.result??null;}
export class GatewayError extends Error{constructor(message,code,details=undefined){super(message);this.name="GatewayError";this.code=code;this.details=details;}}
export class PcOpsGateway{
  constructor({controlPlane,transport,sessionId,managedStore=null,implementationSha="unknown",executorSha="unknown",relaySha="unknown",producerMatrix=null}={}){if(!controlPlane)throw new TypeError("controlPlane is required.");if(!transport)throw new TypeError("transport is required.");if(typeof sessionId!=="string"||!sessionId)throw new TypeError("sessionId is required.");this.controlPlane=controlPlane;this.transport=transport;this.sessionId=sessionId;this.managedStore=managedStore??new ManagedOperationStore();this.implementationSha=implementationSha;this.executorSha=executorSha;this.relaySha=relaySha;this.producerMatrix=producerMatrix;}
  manifest(){return {...toolManifest(),path_policy:pathPolicyContract()};}
  supports(name){if(name==="health.get")return true;if(typeof this.transport.supports==="function")return this.transport.supports(name);return CURRENT_RELAY_BASELINE.includes(name);}
  async health(){const relay=typeof this.transport.health==="function"?await this.transport.health():{},state=this.managedStore.status();return {version:"pc_ops.gateway.health.v1",gateway_version:GATEWAY_VERSION,implementation_sha:this.implementationSha,executor_sha:this.executorSha,relay_sha:this.relaySha,queue_transport:relay,last_request:state.last_request??relay?.last_processed_request??null,last_result:state.last_result??null,path_policy:pathPolicyContract(),ready_to_migrate:this.producerMatrix?.ready_to_migrate??false};}
  #providerArgs(name,args){
    const out=structuredClone(args);
    const operationId=out.operation_id;
    if(START_KIND.has(name)){delete out.operation_id;return out;}
    if(!OPERATION_TOOLS.test(name))return out;
    const op=this.managedStore.get(operationId);
    if(!op)throw new GatewayError("Managed operation was not found.","PC_OPS_OPERATION_NOT_FOUND",{operation_id:operationId});
    const handleId=typeof op.remote_handle==="string"?op.remote_handle:op.remote_handle?.handle_id??op.remote_handle?.session_id??null;
    if(!handleId)throw new GatewayError("Managed operation has no reconciled remote handle; refusing replay or replacement start.","PC_OPS_REMOTE_HANDLE_UNKNOWN",{operation_id:operationId,status:op.status});
    delete out.operation_id;
    if(name.startsWith("process."))out.handle_id=handleId;
    else out.session_id=handleId;
    if((name==="process.read_output"||name==="shell.session.read")&&out.cursor===undefined&&op.cursor!==null)out.cursor=op.cursor;
    if(name==="shell.session.write_stdin"&&Object.hasOwn(out,"data")){out.text=out.data;delete out.data;}
    return out;
  }
  async #settle(actionId){for(let i=0;i<64;i++){const current=this.controlPlane.getAction(actionId);if(TERMINAL.has(current.status)||current.status==="awaiting_confirmation")return current;const processed=await this.controlPlane.processNext({workerId:"pc-ops-gateway"});if(!processed)return this.controlPlane.getAction(actionId);}return this.controlPlane.getAction(actionId);}
  async call(name,rawArgs={},context={}){const meta=getToolMetadata(name);if(!meta)throw new GatewayError("Unknown pc_ops.gateway.v1 tool.","PC_OPS_TOOL_UNKNOWN",{name});const requestId=typeof context.requestId==="string"&&context.requestId?context.requestId:randomUUID();if(name==="health.get"){const out=await this.health();this.managedStore.updateGatewayStatus({last_request:requestId,last_result:{tool:name,status:"succeeded"}});return {request_id:requestId,tool:name,status:"succeeded",data:out};}if(!this.supports(name))throw new GatewayError("The exact-green relay producer does not expose this gateway tool yet.","PC_OPS_PRODUCER_PENDING",{tool:name,producer_requirement:meta.producer_requirement});let args=guardToolPaths(name,rawArgs);args=this.#resolveOperationArgs(name,args);const startKind=START_KIND.get(name);let operation=null;if(startKind){const operationId=args.operation_id??requestId;args.operation_id=operationId;const digestArgs=structuredClone(args);delete digestArgs.operation_id;operation=this.managedStore.ensureStart({operationId,kind:startKind,requestId,tool:name,paramsDigest:digest(digestArgs)});if(operation.start_action_id){const existing=this.controlPlane.getAction(operation.start_action_id),existingData=resultData(existing);if(existing.status==="succeeded"&&existingData?.handle_id)operation=this.managedStore.observe(operationId,{remoteHandle:{handle_id:existingData.handle_id,session_id:existingData.session_id??null},status:existingData.returncode===undefined?"running":"exited",cursor:existingData.cursor});return {request_id:requestId,tool:name,action_id:existing.id,status:existing.status,data:existingData,operation};}}
    const providerArgs=this.#providerArgs(name,args);
    const action=this.controlPlane.enqueueAction(this.sessionId,{provider:"help-pc-1",type:name,input:providerArgs,resource:args.operation_id??args.path??args.source??null,permission:meta.access==="read_only"?"desktop.observe":"desktop.control",idempotencyKey:startKind?"pc-ops:start:"+args.operation_id:requestId,correlationId:requestId,destructive:meta.destructive_level==="high",confirmation:meta.destructive_level==="high"?"required":"none",requiresDesktop:meta.scope==="desktop",metadata:{gateway_version:GATEWAY_VERSION,tool:name,restart_semantics:meta.restart_semantics,external_request_id:requestId,managed_operation_id:args.operation_id??null}});
    if(startKind)operation=this.managedStore.bindAction(args.operation_id,action.id);let settled=action;if(action.status==="awaiting_confirmation"){if(context.confirm===true)settled=this.controlPlane.confirmAction(action.id,{approvedBy:context.approvedBy??"gateway-client"});else{this.managedStore.updateGatewayStatus({last_request:requestId,last_result:{tool:name,status:"awaiting_confirmation",action_id:action.id}});return {request_id:requestId,tool:name,action_id:action.id,status:"awaiting_confirmation",confirmation_required:true,operation};}}
    settled=await this.#settle(settled.id);const data=resultData(settled);if(startKind&&settled.status==="succeeded")operation=this.managedStore.observe(args.operation_id,{remoteHandle:data?.handle_id?{handle_id:data.handle_id,session_id:data.session_id??null}:null,status:data?.handle_id?"running":"completed_without_handle",cursor:data?.cursor});if(OPERATION_TOOLS.test(name)&&args.operation_id&&data?.cursor!==undefined)operation=this.managedStore.observe(args.operation_id,{cursor:data.cursor,status:data.status});if((name==="process.terminate"||name==="shell.session.terminate")&&args.operation_id&&settled.status==="succeeded")operation=this.managedStore.observe(args.operation_id,{status:"terminated"});const envelope={request_id:requestId,tool:name,action_id:settled.id,status:settled.status,data,error:settled.error??null,operation};this.managedStore.updateGatewayStatus({last_request:requestId,last_result:{tool:name,status:settled.status,action_id:settled.id}});return envelope;}
}
