import path from "node:path";
export const PATH_POLICY_VERSION="pc_ops.path_policy.v1";
export const PROTECTED_ROOTS=Object.freeze(["E:\\manhwa"]);
const BYPASS_KEYS=/^(?:safety[_-]?bypass|skip[_-]?policy|disable[_-]?policy|unsafe|force[_-]?unsafe)$/i;
export class PathPolicyError extends Error{constructor(message,code="PC_OPS_PATH_BLOCKED",details=undefined){super(message);this.name="PathPolicyError";this.code=code;this.details=details;}}
export function assertNoSafetyBypass(value,trail="$"){if(!value||typeof value!=="object")return;for(const [key,item] of Object.entries(value)){if(BYPASS_KEYS.test(key))throw new PathPolicyError("Clients cannot request a safety bypass.","PC_OPS_SAFETY_BYPASS_FORBIDDEN",{trail,key});if(item&&typeof item==="object")assertNoSafetyBypass(item,trail+"."+key);}}
export function normalizePcPath(value,{cwd=null}={}){if(typeof value!=="string"||!value.trim())throw new PathPolicyError("Path must be a non-empty string.","PC_OPS_PATH_INVALID");let candidate=value.trim().replaceAll("/","\\");if(!path.win32.isAbsolute(candidate)){if(typeof cwd!=="string"||!path.win32.isAbsolute(cwd.replaceAll("/","\\")))throw new PathPolicyError("Relative paths require an absolute cwd.","PC_OPS_PATH_CWD_REQUIRED");candidate=path.win32.resolve(cwd.replaceAll("/","\\"),candidate);}return path.win32.normalize(candidate);}
function key(value){return value.replace(/[\\/]+$/,"").toLocaleLowerCase("en-US");}
export function isProtectedPath(value,options={}){const normalized=normalizePcPath(value,options),target=key(normalized);return PROTECTED_ROOTS.some((root)=>{const base=key(path.win32.normalize(root));return target===base||target.startsWith(base+"\\");});}
export function assertPathAllowed(value,options={}){const normalized=normalizePcPath(value,options);if(isProtectedPath(normalized))throw new PathPolicyError("Path is protected by PC Operations policy.","PC_OPS_PROTECTED_PATH",{path:"[PROTECTED]"});return normalized;}
export function guardToolPaths(_tool,args={}){assertNoSafetyBypass(args);const copy=structuredClone(args);const cwd=typeof copy.cwd==="string"?assertPathAllowed(copy.cwd):null;if(cwd)copy.cwd=cwd;for(const field of ["path","destination","source","repo_path","log_path"]){if(typeof copy[field]==="string")copy[field]=assertPathAllowed(copy[field],{cwd});}if(Array.isArray(copy.paths))copy.paths=copy.paths.map((p)=>assertPathAllowed(p,{cwd}));return copy;}
export function pathPolicyContract(){return {version:PATH_POLICY_VERSION,protected_roots:["E:\\manhwa"],normalization:"Windows win32 normalize; relative paths require explicit absolute cwd; comparison is case-insensitive; protected root and descendants fail closed.",client_bypass:false};}
