import { mkdirSync } from "node:fs";
import { join,resolve } from "node:path";
import { ControlPlane } from "../control-plane.js";
import { HelpPc1Adapter } from "../adapters.js";
import { JsonStateStore,JsonlAuditTimeline } from "../persistence.js";
import { GitQueueRelayTransport } from "./transport.js";
import { ManagedOperationStore } from "./managed-operations.js";
import { PcOpsGateway } from "./gateway.js";
export function createGatewayRuntime({stateDir,queueRepo,queueRef="agent/pc-relay-queue",desktopId="default",relayDryRun=true,allowDestructive=false,implementationSha="unknown",executorSha="2cc1e40f792a3d74560b726a0d246c90b7f077e9",relaySha="fcea28ec18a7e3a72e43a62c2782b5a51414a32f",producerMatrix=null}={}){const root=resolve(stateDir);mkdirSync(root,{recursive:true});const transport=new GitQueueRelayTransport({queueRepo,queueRef});const provider=new HelpPc1Adapter({dryRun:relayDryRun,invoke:transport.invoke,readCapabilities:transport.readCapabilities,preflight:transport.preflight,readEvidence:transport.readEvidence});const controlPlane=new ControlPlane({providers:[provider],store:new JsonStateStore(join(root,"control-plane.json")),auditTimeline:new JsonlAuditTimeline(join(root,"audit.jsonl")),policy:{permissions:["desktop.observe","desktop.control",...(allowDestructive?["destructive"]:[])],allowDestructive}});let session=controlPlane.listSessions().find((x)=>x.status==="active"&&x.desktopId===desktopId);if(!session)session=controlPlane.createSession({desktopId,principal:"pc-ops-gateway",permissions:["desktop.observe","desktop.control",...(allowDestructive?["destructive"]:[])]});const managedStore=new ManagedOperationStore(join(root,"managed-operations.json"));return new PcOpsGateway({controlPlane,transport,sessionId:session.id,managedStore,implementationSha,executorSha,relaySha,producerMatrix});}
