import { createHash } from "node:crypto";
import { existsSync,mkdirSync,readFileSync,writeFileSync } from "node:fs";
import { dirname,join,resolve } from "node:path";
import { execFileSync } from "node:child_process";
import { CURRENT_RELAY_BASELINE } from "./catalog.js";
import { assertPathAllowed } from "./path-policy.js";
function canonical(value){if(Array.isArray(value))return"["+value.map(canonical).join(",")+"]";if(value&&typeof value==="object")return"{"+Object.keys(value).sort().map((k)=>JSON.stringify(k)+":"+canonical(value[k])).join(",")+"}";return JSON.stringify(value);}
function sha256(value){return createHash("sha256").update(value).digest("hex");} function sleep(ms){return new Promise((r)=>setTimeout(r,ms));}
function cleanId(value){const s=String(value).replace(/[^A-Za-z0-9._-]/g,"-");return s.length<=80?s:s.slice(0,63)+"."+sha256(s).slice(0,16);}
export class GitQueueRelayTransport{
  constructor({queueRepo,queueRef="agent/pc-relay-queue",heartbeatId="default",pollMs=1000,resultTimeoutMs=130000,supportedActions=CURRENT_RELAY_BASELINE}={}){this.queueRepo=resolve(assertPathAllowed(queueRepo));this.queueRef=queueRef;this.heartbeatId=heartbeatId;this.pollMs=pollMs;this.resultTimeoutMs=resultTimeoutMs;this.supported=new Set(supportedActions);if(!existsSync(join(this.queueRepo,".git")))throw Object.assign(new Error("queueRepo must be a Git checkout."),{code:"PC_OPS_QUEUE_INVALID"});}
  supports(name){return this.supported.has(name);}
  #git(args){try{return execFileSync("git",args,{cwd:this.queueRepo,encoding:"utf8",windowsHide:true,stdio:["ignore","pipe","pipe"]}).trim();}catch{const e=new Error("Git relay transport command failed without exposing stderr.");e.code="PC_OPS_GIT_TRANSPORT_FAILED";e.command=String(args[0]??"git");throw e;}}
  sync(){const branch=this.#git(["rev-parse","--abbrev-ref","HEAD"]);if(branch!==this.queueRef)throw Object.assign(new Error("Queue checkout is on the wrong branch."),{code:"PC_OPS_QUEUE_REF_MISMATCH"});this.#git(["fetch","origin",this.queueRef]);this.#git(["merge","--ff-only","origin/"+this.queueRef]);return this.#git(["rev-parse","HEAD"]);}
  #publish(request){this.sync();const rel="relay/requests/"+request.id+".json",full=join(this.queueRepo,...rel.split("/")),bytes=JSON.stringify(request,null,2)+"\n";if(existsSync(full)){const existing=JSON.parse(readFileSync(full,"utf8"));if(existing.request_sha256!==request.request_sha256)throw Object.assign(new Error("Immutable relay request id conflicts with existing content."),{code:"PC_OPS_QUEUE_ID_CONFLICT"});return;}mkdirSync(dirname(full),{recursive:true});writeFileSync(full,bytes,{encoding:"utf8",mode:0o600});this.#git(["add","--",rel]);this.#git(["commit","-m","pc-ops request "+request.id,"--",rel]);try{this.#git(["push","origin","HEAD:"+this.queueRef]);}catch{try{this.#git(["pull","--rebase","origin",this.queueRef]);this.#git(["push","origin","HEAD:"+this.queueRef]);}catch(second){try{this.#git(["rebase","--abort"]);}catch{}throw second;}}}
  async #waitResult(id,timeoutMs){const full=join(this.queueRepo,"relay","results",id+".json"),deadline=Date.now()+timeoutMs;while(Date.now()<deadline){this.sync();if(existsSync(full))return JSON.parse(readFileSync(full,"utf8"));await sleep(this.pollMs);}const e=new Error("Relay result timed out; outcome must be reconciled before replay.");e.code="PC_OPS_RELAY_TIMEOUT";e.dispatchState="unknown";e.outcomeUncertain=true;throw e;}
  async #relay(id,action,params={},timeoutMs=120000){const body={version:"pc_relay.request.v2",id:cleanId(id),action,params,timeout_ms:Math.min(120000,Math.max(100,timeoutMs)),note:"pc_ops.gateway.v1"};body.request_sha256=sha256(canonical(body));this.#publish(body);const result=await this.#waitResult(body.id,Math.max(this.resultTimeoutMs,body.timeout_ms+10000));if(result.request_sha256!==body.request_sha256)throw Object.assign(new Error("Relay result binding mismatch."),{code:"PC_OPS_RELAY_BINDING_MISMATCH",dispatchState:"unknown",outcomeUncertain:true});if(result.relay_status==="reconciliation_required"){const e=new Error("Relay reported unknown side-effect outcome.");e.code="PC_OPS_RECONCILIATION_REQUIRED";e.dispatchState="unknown";e.outcomeUncertain=true;throw e;}if(result.relay_status==="relay_error"&&!result.executor_result){const e=new Error("Relay transport reported execution failure.");e.code="PC_OPS_RELAY_ERROR";e.dispatchState="unknown";e.outcomeUncertain=true;throw e;}return result.executor_result??result;}
  invoke=(request)=>this.#relay(request.request_id,request.action,request.params??{},120000);
  readCapabilities=({request_id})=>this.#relay(cleanId(request_id+".cap"),"capabilities.get",{},30000);
  preflight=(request)=>this.#relay(cleanId(request.request_id+".pre."+sha256(canonical(request)).slice(0,12)),"action.preflight",request,30000);
  readEvidence=({request_id,action,execution_attempt})=>this.#relay(cleanId(request_id+".outcome."+String(execution_attempt??0)),"outcome.lookup",{request_id,action,execution_attempt},30000);
  async health(){let queue_head=null,queue_reachable=true;try{queue_head=this.sync();}catch{queue_reachable=false;}const full=join(this.queueRepo,"relay","heartbeat",cleanId(this.heartbeatId)+".json");let heartbeat=null;if(existsSync(full)){try{heartbeat=JSON.parse(readFileSync(full,"utf8"));}catch{}}return {transport:"github_git_relay",queue_ref:this.queueRef,queue_head,queue_reachable,relay_alive:heartbeat?.relay_alive??null,executor_available:heartbeat?.executor_available??null,queue_integrity:heartbeat?.queue_integrity??null,last_processed_request:heartbeat?.last_processed_request??null,relay_implementation_sha:heartbeat?.implementation_sha??null};}
}
